version: "2.4"
services:
  reverse-proxy:
    image: bitnami/nginx:1.22.0-debian-11-r16
    user: ${REVERSE_PROXY_CONTAINER_USER}
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - ${NGINX_CONF}:/opt/bitnami/nginx/conf/server_blocks/vhost.conf:ro
      - ${NGINX_CERT}:/opt/bitnami/nginx/conf/server.crt:ro
      - ${NGINX_KEY}:/opt/bitnami/nginx/conf/server.key:ro
    depends_on:
      web:
        condition: service_healthy
      database:
        condition: service_healthy
  web:
    image: ghcr.io/philanthropydatacommons/service:20220929-30746b0
    user: ${WEB_CONTAINER_USER}
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - PGHOST=database
      - PGUSER=${PG_USER}
      - PGPASSWORD=${PG_PASS}
      - PGDATABASE=${PG_DB}
      - PGPORT=${PG_PORT}
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://web:3000"]
    depends_on:
      database:
        condition: service_healthy
  database:
    image: bitnami/postgresql:14.4.0-debian-11-r9
    user: ${DATABASE_CONTAINER_USER}
    volumes:
      - ${PG_DATA}:/bitnami/postgresql
      # In order for psql to use an arbitrary user above:
      - /etc/passwd:/etc/passwd:ro
      # In order for psql to save command history:
      - ${PG_DATA}:/var/lib/postgresql
      # In order to extend/override configuration while keeping a generated one:
      - ${PG_DATA}/conf/conf.d:/bitnami/postgresql/conf/conf.d:ro
    environment:
      - POSTGRESQL_USERNAME=${PG_USER}
      - POSTGRESQL_PASSWORD=${PG_PASS}
      - POSTGRESQL_DATABASE=${PG_DB}
      - POSTGRESQL_PORT_NUMBER=${PG_PORT}
      - POSTGRESQL_POSTGRES_PASSWORD=${PG_POSTGRES_PASS}
    healthcheck:
      test: ["CMD", "pg_isready", "-q",
             "-d", "${PG_DB}",
             "-U", "${PG_USER}",
             "-p", "${PG_PORT}"]
