version: "2.4"
services:
  reverse-proxy:
    image: bitnami/nginx:1.23.3-debian-11-r10
    user: ${REVERSE_PROXY_CONTAINER_USER}
    ports:
      # Purposely omit port 80 in order to run ACME clients standalone.
      - "443:8443"
    volumes:
      - ${NGINX_CONF}:/opt/bitnami/nginx/conf/server_blocks/vhost.conf:ro
      - ${NGINX_CERT}:/opt/bitnami/nginx/conf/server.crt:ro
      - ${NGINX_KEY}:/opt/bitnami/nginx/conf/server.key:ro
    depends_on:
      web:
        condition: service_healthy
      database:
        condition: service_healthy
    logging:
      driver: journald
  web:
    image: ghcr.io/philanthropydatacommons/service:20230214-69568c5
    user: ${WEB_CONTAINER_USER}
    volumes:
      - ${API_KEYS_FILE}:${API_KEYS_FILE}:ro
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - PGHOST=database
      - PGUSER=${PG_USER}
      - PGPASSWORD=${PG_PASS}
      - PGDATABASE=${PG_DB}
      - PGPORT=${PG_PORT}
      - API_KEYS_FILE=${API_KEYS_FILE}
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://web:3000"]
      interval: 10s
    depends_on:
      database:
        condition: service_healthy
    logging:
      driver: journald
  database:
    image: bitnami/postgresql:14.6.0-debian-11-r20
    user: ${DATABASE_CONTAINER_USER}
    volumes:
      - ${PG_DATA}:/bitnami/postgresql
      # In order for psql to use an arbitrary user above:
      - /etc/passwd:/etc/passwd:ro
      # In order for psql to save command history:
      - ${PG_DATA}:/var/lib/postgresql
      # In order to extend/override configuration while keeping a generated one:
      - ${PG_DATA}/conf/conf.d:/bitnami/postgresql/conf/conf.d:ro
      # In order to run a script to create keycloak database:
      - ${KEYCLOAK_PG_INITDB_SCRIPT}:/docker-entrypoint-initdb.d/keycloak.sh
    environment:
      - POSTGRESQL_USERNAME=${PG_USER}
      - POSTGRESQL_PASSWORD=${PG_PASS}
      - POSTGRESQL_DATABASE=${PG_DB}
      - POSTGRESQL_PORT_NUMBER=${PG_PORT}
      - POSTGRESQL_POSTGRES_PASSWORD=${PG_POSTGRES_PASS}
      - KEYCLOAK_PG_PASSWORD=${KEYCLOAK_PG_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-q",
             "-d", "${PG_DB}",
             "-U", "${PG_USER}",
             "-p", "${PG_PORT}"]
      interval: 10s
    logging:
      driver: journald
  auth:
    # Do not expose any ports here. Allow access via reverse-proxy or overlay.
    image: bitnami/keycloak:20.0.2-debian-11-r9
    user: ${AUTH_CONTAINER_USER}
    environment:
      - KEYCLOAK_DATABASE_HOST=database
      - KEYCLOAK_DATABASE_PORT=${PG_PORT}
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_USER=keycloak
      - KEYCLOAK_DATABASE_SCHEMA=public
      - KEYCLOAK_DATABASE_PASSWORD=${KEYCLOAK_PG_PASSWORD}
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KEYCLOAK_MANAGEMENT_USER=management
      - KEYCLOAK_MANAGEMENT_PASSWORD=${KEYCLOAK_MANAGEMENT_PASSWORD}
      - KEYCLOAK_EXTRA_ARGS=--proxy=edge --hostname-path=/auth --http-relative-path=/auth --hostname-strict=false
    depends_on:
      database:
        condition: service_healthy
    logging:
      driver: journald
