on:
  pull_request:
  push:

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    env:
      SHELLCHECK_OPTS: -x
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
