name: Update service image

on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'The tag of the docker image to use'
        required: true
        type: string

jobs:
  update-service-image:
    runs-on: ubuntu-latest
    environment: build
    steps:
    - uses: actions/checkout@v2
      with:
        ssh-key: "${{ secrets.SSH_PUSH_DEPLOY_PRIVATE_KEY }}"
    - run: git config --global user.email "update-service-image-bot@github.com"
    - run: git config --global user.name "Update Service Image Bot"
    - run: sed -i "s/ghcr\.io\/philanthropydatacommons\/service:[0-9a-z_-]*/ghcr\.io\/philanthropydatacommons\/service:${{ github.event.inputs.image-tag }}/" compose.yml
    - run: git diff
    - run: git add compose.yml
    - run: git commit -m "Auto-update service image to ${{ github.event.inputs.image-tag }}"
    - run: git log --graph --decorate --all
    - run: git push
    # Note the following VERSION is of this repo, of the compose.yml,
    # which is distinct from the service image version from the service
    # repo passed in above. Multiple components exist in the compose
    # file and also configuration so it has a separate version.
    - run: echo VERSION=$(git log -1 --date=unix --pretty=format:"%cd" | date --utc +%Y%m%d)-$(git log -1 --pretty=format:"%h") >> $GITHUB_ENV
    - run: git tag ${{ env.VERSION }}
    - run: git push origin ${{ env.VERSION }}
